import { useState, useEffect, useRef, useCallback } from 'react';
import toast from 'react-hot-toast';
import { useWebSocket } from '../hooks/useWebSocket';

const API_BASE = (import.meta.env.VITE_API_URL || 'http://localhost:3001/api').replace(/\/api$/, '');

/**
 * AICourseStructureModal - Modal for generating course structure using AI
 *
 * Steps:
 * 1. User provides topic and learning goals
 * 2. AI generates course structure with modules and lessons
 * 3. User reviews and modifies suggestions
 * 4. User saves AI-generated structure to course
 */
export default function AICourseStructureModal({
  isOpen,
  onClose,
  courseId,
  onStructureApplied,
  // Pre-filled course data from CourseCreatorPage
  courseTitle = '',
  courseDescription = '',
  courseLevel = 'Principiante',
  courseCategory = '',
  courseObjectives = []
}) {
  const [step, setStep] = useState(1); // 1: input, 2: review, 3: batch content generation
  const [isGenerating, setIsGenerating] = useState(false);
  const [isApplying, setIsApplying] = useState(false);

  // Input state - pre-filled from course data
  const [topic, setTopic] = useState('');
  const [goals, setGoals] = useState('');
  const [level, setLevel] = useState('Principiante');
  const [targetAudience, setTargetAudience] = useState('');

  // Track if we have pre-filled data
  const hasPrefilledData = !!(courseTitle && (courseDescription || courseObjectives.length > 0));
  const hasAutoGenerated = useRef(false);

  // Generated structure state
  const [generatedStructure, setGeneratedStructure] = useState(null);
  const [editingModuleIndex, setEditingModuleIndex] = useState(null);
  const [ragSources, setRagSources] = useState([]);
  const [generationMetadata, setGenerationMetadata] = useState(null);

  // Batch content generation state (Step 3)
  const [batchId, setBatchId] = useState(null);
  const [batchProgress, setBatchProgress] = useState(null); // { currentLesson, totalLessons, status }
  const [batchLessonStatuses, setBatchLessonStatuses] = useState({}); // lessonId -> { status, contentLength, error }
  const [batchComplete, setBatchComplete] = useState(false);
  const [batchSummary, setBatchSummary] = useState(null); // { completed, failed, total, cancelled }
  const [appliedLessonsCount, setAppliedLessonsCount] = useState(0);

  // WebSocket for batch progress
  const ws = useWebSocket();

  // Pre-fill form when modal opens with course data
  useEffect(() => {
    if (isOpen && courseTitle) {
      setTopic(courseTitle);
      // Use objectives if available, otherwise use description
      if (courseObjectives.length > 0) {
        setGoals(courseObjectives.join('\n'));
      } else if (courseDescription) {
        setGoals(courseDescription);
      }
      setLevel(courseLevel || 'Principiante');
      setTargetAudience(courseCategory || '');
    }
  }, [isOpen, courseTitle, courseDescription, courseLevel, courseCategory, courseObjectives]);

  // Auto-generate when modal opens with pre-filled data
  useEffect(() => {
    if (isOpen && hasPrefilledData && !hasAutoGenerated.current && !generatedStructure) {
      hasAutoGenerated.current = true;
      // Small delay to ensure state is set
      const timer = setTimeout(() => {
        const goalsData = courseObjectives.length > 0 ? courseObjectives.join('\n') : courseDescription;
        handleGenerateWithData(courseTitle, goalsData, courseLevel, courseCategory);
      }, 200);
      return () => clearTimeout(timer);
    }
  }, [isOpen, hasPrefilledData, generatedStructure]);

  // Reset auto-generate flag when modal closes
  useEffect(() => {
    if (!isOpen) {
      hasAutoGenerated.current = false;
    }
  }, [isOpen]);

  // WebSocket: connect and listen for batch progress
  useEffect(() => {
    if (!batchId) return;

    ws.connect();

    const cleanupProgress = ws.onMessage('batch_content_progress', (data) => {
      if (data.batchId !== batchId) return;

      setBatchProgress({
        currentLesson: data.currentLesson,
        totalLessons: data.totalLessons,
        lessonTitle: data.lessonTitle,
        moduleTitle: data.moduleTitle,
        status: data.status
      });

      if (data.status === 'completed' || data.status === 'failed') {
        setBatchLessonStatuses(prev => ({
          ...prev,
          [data.lessonId]: {
            status: data.status,
            contentLength: data.contentLength || 0,
            error: data.error || null,
            title: data.lessonTitle,
            moduleTitle: data.moduleTitle
          }
        }));
      }
    });

    const cleanupComplete = ws.onMessage('batch_content_complete', (data) => {
      if (data.batchId !== batchId) return;

      setBatchComplete(true);
      setBatchSummary({
        completed: data.completed,
        failed: data.failed,
        total: data.total,
        cancelled: data.cancelled,
        errors: data.errors || []
      });
    });

    return () => {
      cleanupProgress();
      cleanupComplete();
    };
  }, [batchId, ws]);

  // Restore saved structure from localStorage when modal opens
  useEffect(() => {
    if (!isOpen || !courseId || generatedStructure) return;

    try {
      const raw = localStorage.getItem(`ai_course_structure_${courseId}`);
      if (!raw) return;
      const saved = JSON.parse(raw);

      // Check expiration (24 hours)
      const savedAt = new Date(saved.savedAt);
      const hoursAgo = (Date.now() - savedAt.getTime()) / (1000 * 60 * 60);
      if (hoursAgo > 24) {
        localStorage.removeItem(`ai_course_structure_${courseId}`);
        return;
      }

      if (saved.generatedStructure) {
        setGeneratedStructure(saved.generatedStructure);
        setRagSources(saved.ragSources || []);
        setGenerationMetadata(saved.generationMetadata || null);
        setTopic(saved.topic || '');
        setGoals(saved.goals || '');
        setLevel(saved.level || 'Principiante');
        setTargetAudience(saved.targetAudience || '');
        setStep(2);
        hasAutoGenerated.current = true;
        toast.success('Estructura anterior restaurada');
      }
    } catch {
      // Ignore parse errors
    }
  }, [isOpen, courseId]); // eslint-disable-line react-hooks/exhaustive-deps

  // Generate with specific data (for auto-generation)
  const handleGenerateWithData = async (topicData, goalsData, levelData, audienceData) => {
    if (!topicData?.trim() || !goalsData?.trim()) {
      setStep(1); // Show input form if data is incomplete
      return;
    }

    setIsGenerating(true);
    try {
      const response = await fetch(`${API_BASE}/api/ai/generate-course-structure`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({
          topic: topicData,
          goals: goalsData,
          level: levelData || 'Principiante',
          targetAudience: audienceData || ''
        })
      });

      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.error || 'Error al generar estructura');
      }

      const data = await response.json();
      setGeneratedStructure(data.structure);
      setRagSources(data.sources || []);
      setGenerationMetadata(data.metadata || null);
      setStep(2);

      const sourcesMsg = data.sources?.length > 0 ? ` usando ${data.sources.length} fuentes` : '';
      toast.success(`Se generaron ${data.structure.modules.length} modulos${sourcesMsg}`);
    } catch (error) {
      console.error('Error generating structure:', error);
      toast.error(error.message || 'Error al generar la estructura');
      // If auto-generation fails, show the input form
      setStep(1);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleGenerate = async () => {
    if (!topic.trim()) {
      toast.error('El tema del curso es obligatorio');
      return;
    }

    if (!goals.trim()) {
      toast.error('Los objetivos de aprendizaje son obligatorios');
      return;
    }

    setIsGenerating(true);
    try {
      const response = await fetch(`${API_BASE}/api/ai/generate-course-structure`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({
          topic,
          goals,
          level,
          targetAudience
        })
      });

      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.error || 'Error al generar estructura');
      }

      const data = await response.json();
      setGeneratedStructure(data.structure);
      setRagSources(data.sources || []);
      setGenerationMetadata(data.metadata || null);
      setStep(2);

      const sourcesMsg = data.sources?.length > 0 ? ` usando ${data.sources.length} fuentes` : '';
      toast.success(`Se generaron ${data.structure.modules.length} modulos${sourcesMsg}`);
    } catch (error) {
      console.error('Error generating structure:', error);
      toast.error(error.message || 'Error al generar la estructura');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleEditModule = (index) => {
    setEditingModuleIndex(index);
  };

  const handleSaveModuleEdit = (index, updatedModule) => {
    const updated = { ...generatedStructure };
    updated.modules[index] = updatedModule;
    setGeneratedStructure(updated);
    setEditingModuleIndex(null);
    toast.success('Modulo actualizado');
  };

  const handleDeleteModule = (index) => {
    if (generatedStructure.modules.length <= 1) {
      toast.error('El curso debe tener al menos un modulo');
      return;
    }
    const updated = { ...generatedStructure };
    updated.modules = updated.modules.filter((_, i) => i !== index);
    setGeneratedStructure(updated);
    toast.success('Modulo eliminado');
  };

  const handleApplyStructure = async () => {
    if (!generatedStructure || generatedStructure.modules.length === 0) {
      toast.error('No hay estructura para aplicar');
      return;
    }

    setIsApplying(true);
    try {
      const response = await fetch(`${API_BASE}/api/ai/apply-course-structure/${courseId}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({
          modules: generatedStructure.modules
        })
      });

      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.error || 'Error al aplicar estructura');
      }

      const data = await response.json();
      toast.success(data.message || 'Estructura aplicada exitosamente');

      // Count total lessons for step 3
      const totalLessons = generatedStructure.modules.reduce(
        (sum, m) => sum + (m.lessons?.length || 0), 0
      );
      setAppliedLessonsCount(totalLessons);

      // Transition to step 3 instead of closing
      setStep(3);

      // Clean up saved structure from localStorage
      if (courseId) {
        localStorage.removeItem(`ai_course_structure_${courseId}`);
      }
    } catch (error) {
      console.error('Error applying structure:', error);
      toast.error(error.message || 'Error al aplicar la estructura');
    } finally {
      setIsApplying(false);
    }
  };

  // Start batch content generation
  const handleStartBatchGeneration = async () => {
    try {
      const response = await fetch(`${API_BASE}/api/ai/batch-generate-course-content/${courseId}`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include'
      });

      if (!response.ok) {
        const error = await response.json();
        throw new Error(error.error || 'Error al iniciar generacion');
      }

      const data = await response.json();
      setBatchId(data.batchId);
      setAppliedLessonsCount(data.totalLessons);
      setBatchComplete(false);
      setBatchSummary(null);
      setBatchLessonStatuses({});
      setBatchProgress(null);
      toast.success(`Generando contenido para ${data.totalLessons} lecciones...`);
    } catch (error) {
      console.error('Error starting batch generation:', error);
      toast.error(error.message || 'Error al iniciar generacion de contenido');
    }
  };

  // Cancel batch generation
  const handleCancelBatch = async () => {
    if (!batchId) return;

    try {
      await fetch(`${API_BASE}/api/ai/batch-cancel/${batchId}`, {
        method: 'POST',
        credentials: 'include'
      });
      toast('Cancelando generacion...', { icon: '\u26A0\uFE0F' });
    } catch (error) {
      console.error('Error cancelling batch:', error);
    }
  };

  // Finish step 3 and close modal
  const handleFinishAndClose = () => {
    if (courseId) {
      localStorage.removeItem(`ai_course_structure_${courseId}`);
    }
    if (onStructureApplied) {
      onStructureApplied({ reload: true });
    }
    handleClose();
  };

  const handleClose = () => {
    // Persist structure to localStorage if closing at step 2 with generated structure
    if (step === 2 && generatedStructure && courseId) {
      try {
        localStorage.setItem(`ai_course_structure_${courseId}`, JSON.stringify({
          generatedStructure,
          ragSources,
          generationMetadata,
          topic,
          goals,
          level,
          targetAudience,
          savedAt: new Date().toISOString()
        }));
      } catch {
        // Ignore storage errors
      }
    }

    setStep(1);
    setTopic('');
    setGoals('');
    setLevel('Principiante');
    setTargetAudience('');
    setGeneratedStructure(null);
    setEditingModuleIndex(null);
    setRagSources([]);
    setGenerationMetadata(null);
    // Reset step 3 state
    setBatchId(null);
    setBatchProgress(null);
    setBatchLessonStatuses({});
    setBatchComplete(false);
    setBatchSummary(null);
    setAppliedLessonsCount(0);
    onClose();
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div className="bg-white dark:bg-gray-800 rounded-xl shadow-xl w-full max-w-4xl max-h-[90vh] overflow-hidden flex flex-col">
        {/* Header */}
        <div className="px-6 py-4 border-b border-gray-200 dark:border-gray-700 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-gradient-to-br from-green-500 to-blue-600 rounded-lg flex items-center justify-center">
              <svg className="w-6 h-6 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
              </svg>
            </div>
            <div>
              <h2 className="text-lg font-semibold text-gray-900 dark:text-white">
                Generar Estructura con IA
              </h2>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                {step === 1 && isGenerating && hasPrefilledData && 'Generando estructura con los datos del curso...'}
                {step === 1 && !isGenerating && 'Proporciona tema y objetivos'}
                {step === 2 && 'Revisa y modifica la estructura generada'}
                {step === 3 && !batchId && 'Estructura aplicada - Genera el contenido'}
                {step === 3 && batchId && !batchComplete && 'Generando contenido con IA...'}
                {step === 3 && batchComplete && 'Generacion completada'}
              </p>
            </div>
          </div>
          <button
            onClick={handleClose}
            className="p-2 text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 transition-colors"
            aria-label="Cerrar modal"
            title="Cerrar"
          >
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6">
          {/* Auto-generating spinner */}
          {step === 1 && isGenerating && hasPrefilledData && (
            <div className="flex flex-col items-center justify-center py-16 space-y-4">
              <svg className="w-12 h-12 animate-spin text-primary-600" fill="none" viewBox="0 0 24 24">
                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
              </svg>
              <p className="text-gray-600 dark:text-gray-400 text-center">
                Generando estructura para <strong>{courseTitle}</strong>...
              </p>
              <p className="text-sm text-gray-500 dark:text-gray-500">
                Usando datos del curso y base de conocimiento RAG
              </p>
            </div>
          )}

          {/* Step 1: Input (shown only when not auto-generating) */}
          {step === 1 && !(isGenerating && hasPrefilledData) && (
            <div className="space-y-6">
              {/* Topic */}
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Tema del Curso *
                </label>
                <input
                  type="text"
                  value={topic}
                  onChange={(e) => setTopic(e.target.value)}
                  className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-primary-500"
                  placeholder="Ej: Python para principiantes, Machine Learning, Desarrollo Web..."
                />
              </div>

              {/* Goals */}
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  Objetivos de Aprendizaje *
                </label>
                <p className="text-sm text-gray-500 dark:text-gray-400 mb-2">
                  Describe que deberian aprender los estudiantes al completar el curso
                </p>
                <textarea
                  value={goals}
                  onChange={(e) => setGoals(e.target.value)}
                  rows={4}
                  className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-primary-500"
                  placeholder="Ej: Dominar las bases de Python, crear funciones, trabajar con estructuras de datos, desarrollar un proyecto practico..."
                />
              </div>

              {/* Level and Audience */}
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Nivel
                  </label>
                  <select
                    value={level}
                    onChange={(e) => setLevel(e.target.value)}
                    className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-primary-500"
                  >
                    <option value="Principiante">Principiante</option>
                    <option value="Intermedio">Intermedio</option>
                    <option value="Avanzado">Avanzado</option>
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Audiencia (opcional)
                  </label>
                  <input
                    type="text"
                    value={targetAudience}
                    onChange={(e) => setTargetAudience(e.target.value)}
                    className="w-full px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 focus:ring-primary-500"
                    placeholder="Ej: Estudiantes universitarios, profesionales..."
                  />
                </div>
              </div>

              {/* Quick Topics */}
              <div>
                <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                  O selecciona un tema popular
                </label>
                <div className="flex flex-wrap gap-2">
                  {['Python', 'JavaScript', 'Data Science', 'Machine Learning', 'SQL', 'React', 'Node.js'].map((t) => (
                    <button
                      key={t}
                      onClick={() => setTopic(t)}
                      className={`px-3 py-1.5 rounded-full text-sm font-medium transition-colors ${
                        topic === t
                          ? 'bg-primary-100 text-primary-700 dark:bg-primary-900 dark:text-primary-300'
                          : 'bg-gray-100 text-gray-700 dark:bg-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600'
                      }`}
                    >
                      {t}
                    </button>
                  ))}
                </div>
              </div>
            </div>
          )}

          {/* Step 2: Review and Edit */}
          {step === 2 && generatedStructure && (
            <div className="space-y-6">
              {/* Suggested Info */}
              <div className="bg-green-50 dark:bg-green-900/20 rounded-lg p-4 border border-green-200 dark:border-green-800">
                <div className="flex items-start gap-3">
                  <svg className="w-6 h-6 text-green-600 dark:text-green-400 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                  <div className="flex-1">
                    <h3 className="font-medium text-green-800 dark:text-green-300">
                      {generatedStructure.suggestedTitle}
                    </h3>
                    <p className="text-sm text-green-700 dark:text-green-400 mt-1">
                      {generatedStructure.suggestedDescription}
                    </p>
                    <div className="flex flex-wrap items-center gap-4 mt-2 text-sm text-green-600 dark:text-green-500">
                      <span>📚 {generatedStructure.modules.length} modulos</span>
                      <span>⏱️ ~{generatedStructure.estimatedDurationHours} horas</span>
                      <span>🎯 {generatedStructure.level}</span>
                    </div>
                  </div>
                </div>
              </div>

              {/* RAG Sources Info */}
              {ragSources.length > 0 && (
                <div className="bg-purple-50 dark:bg-purple-900/20 rounded-lg p-3 border border-purple-200 dark:border-purple-800">
                  <div className="flex items-center gap-2 mb-2">
                    <svg className="w-4 h-4 text-purple-600 dark:text-purple-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
                    </svg>
                    <span className="text-sm font-medium text-purple-700 dark:text-purple-300">
                      Generado con IA + RAG
                    </span>
                  </div>
                  <p className="text-xs text-purple-600 dark:text-purple-400">
                    Fuentes consultadas: {ragSources.map(s => s.book).filter((v, i, a) => a.indexOf(v) === i).slice(0, 3).join(', ')}
                    {ragSources.length > 3 && ` y ${ragSources.length - 3} más`}
                  </p>
                  {generationMetadata?.provider && (
                    <p className="text-xs text-purple-500 dark:text-purple-500 mt-1">
                      Modelo: {generationMetadata.provider === 'local' ? 'DGX Spark (Qwen3-14B)' : 'Claude'}
                    </p>
                  )}
                </div>
              )}

              {/* Learning Objectives */}
              <div>
                <h3 className="font-medium text-gray-900 dark:text-white mb-3 flex items-center gap-2">
                  <svg className="w-5 h-5 text-primary-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-6 9l2 2 4-4" />
                  </svg>
                  Objetivos de Aprendizaje
                </h3>
                <ul className="space-y-2">
                  {generatedStructure.learningObjectives.map((obj, index) => (
                    <li key={index} className="flex items-start gap-2 text-sm text-gray-600 dark:text-gray-400">
                      <span className="text-primary-600">•</span>
                      {obj}
                    </li>
                  ))}
                </ul>
              </div>

              {/* Modules List */}
              <div className="space-y-4">
                <h3 className="font-medium text-gray-900 dark:text-white flex items-center gap-2">
                  <span>Modulos del Curso</span>
                  <span className="px-2 py-0.5 bg-primary-100 text-primary-700 dark:bg-primary-900 dark:text-primary-300 rounded-full text-sm">
                    {generatedStructure.modules.length}
                  </span>
                </h3>

                {generatedStructure.modules.map((module, moduleIndex) => (
                  <div
                    key={moduleIndex}
                    className="border border-gray-200 dark:border-gray-600 rounded-lg overflow-hidden"
                  >
                    {editingModuleIndex === moduleIndex ? (
                      <ModuleEditor
                        module={module}
                        onSave={(updated) => handleSaveModuleEdit(moduleIndex, updated)}
                        onCancel={() => setEditingModuleIndex(null)}
                      />
                    ) : (
                      <div className="p-4">
                        <div className="flex items-start justify-between gap-4">
                          <div className="flex-1">
                            <div className="flex items-center gap-2 mb-2">
                              <span className="w-8 h-8 bg-primary-100 text-primary-700 dark:bg-primary-900 dark:text-primary-300 rounded-full flex items-center justify-center text-sm font-medium">
                                {moduleIndex + 1}
                              </span>
                              <h4 className="font-medium text-gray-900 dark:text-white">
                                {module.title}
                              </h4>
                            </div>
                            <p className="text-sm text-gray-500 dark:text-gray-400 mb-3 ml-10">
                              {module.description}
                            </p>

                            {/* Lessons */}
                            <div className="ml-10 space-y-1">
                              {module.lessons.map((lesson, lessonIndex) => (
                                <div
                                  key={lessonIndex}
                                  className="text-sm py-2 px-3 bg-gray-50 dark:bg-gray-700 rounded space-y-2"
                                >
                                  <div className="flex items-center justify-between">
                                    <span className="text-gray-700 dark:text-gray-300 font-medium">
                                      {lessonIndex + 1}. {lesson.title}
                                    </span>
                                    <span className="text-gray-500 dark:text-gray-400">
                                      {lesson.duration_minutes} min
                                    </span>
                                  </div>
                                  {/* 4C Pedagogical Structure */}
                                  {lesson.structure_4c && (
                                    <div className="mt-2 pt-2 border-t border-gray-200 dark:border-gray-600">
                                      <div className="text-xs font-medium text-primary-600 dark:text-primary-400 mb-1">
                                        Estructura 4C:
                                      </div>
                                      <div className="grid grid-cols-2 gap-2 text-xs">
                                        <div className="flex items-start gap-1">
                                          <span className="text-blue-600 dark:text-blue-400">🔗</span>
                                          <span className="text-gray-600 dark:text-gray-400">Conexiones</span>
                                        </div>
                                        <div className="flex items-start gap-1">
                                          <span className="text-green-600 dark:text-green-400">💡</span>
                                          <span className="text-gray-600 dark:text-gray-400">Conceptos</span>
                                        </div>
                                        <div className="flex items-start gap-1">
                                          <span className="text-orange-600 dark:text-orange-400">🛠️</span>
                                          <span className="text-gray-600 dark:text-gray-400">Practica</span>
                                        </div>
                                        <div className="flex items-start gap-1">
                                          <span className="text-purple-600 dark:text-purple-400">🎯</span>
                                          <span className="text-gray-600 dark:text-gray-400">Conclusion</span>
                                        </div>
                                      </div>
                                    </div>
                                  )}
                                </div>
                              ))}
                            </div>
                          </div>
                          <div className="flex items-center gap-1">
                            <button
                              onClick={() => handleEditModule(moduleIndex)}
                              className="p-2 text-gray-400 hover:text-primary-600 transition-colors"
                              title="Editar"
                              aria-label="Editar modulo"
                            >
                              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                              </svg>
                            </button>
                            <button
                              onClick={() => handleDeleteModule(moduleIndex)}
                              className="p-2 text-gray-400 hover:text-red-600 transition-colors"
                              title="Eliminar"
                              aria-label="Eliminar modulo"
                            >
                              <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                              </svg>
                            </button>
                          </div>
                        </div>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Step 3: Batch Content Generation */}
          {step === 3 && (
            <div className="space-y-6">
              {/* Pre-batch: Offer to generate content */}
              {!batchId && (
                <div className="text-center py-8">
                  <div className="w-16 h-16 mx-auto bg-green-100 dark:bg-green-900/30 rounded-full flex items-center justify-center mb-4">
                    <svg className="w-8 h-8 text-green-600 dark:text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                  </div>
                  <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">
                    Estructura Aplicada Exitosamente
                  </h3>
                  <p className="text-gray-600 dark:text-gray-400 mb-6 max-w-md mx-auto">
                    La estructura del curso fue creada. Ahora puedes generar automaticamente el contenido completo
                    (explicaciones, ejemplos, ejercicios y dinamicas) para las <strong>{appliedLessonsCount} lecciones</strong>.
                  </p>
                  <div className="flex flex-col items-center gap-3">
                    <button
                      onClick={handleStartBatchGeneration}
                      className="flex items-center gap-2 px-8 py-3 bg-gradient-to-r from-green-600 to-blue-600 text-white rounded-lg hover:from-green-700 hover:to-blue-700 transition-colors font-medium"
                    >
                      <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                      </svg>
                      Generar Todo el Contenido
                    </button>
                    <button
                      onClick={handleFinishAndClose}
                      className="text-sm text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300 transition-colors"
                    >
                      Omitir - lo hare manualmente
                    </button>
                  </div>
                </div>
              )}

              {/* Active batch: Progress display */}
              {batchId && !batchComplete && (
                <div className="space-y-4">
                  {/* Progress header */}
                  <div className="flex items-center justify-between">
                    <h3 className="font-medium text-gray-900 dark:text-white">
                      Generando Contenido del Curso
                    </h3>
                    {batchProgress && (
                      <span className="text-sm font-medium text-primary-600 dark:text-primary-400">
                        [{batchProgress.currentLesson}/{batchProgress.totalLessons}] {Math.round((batchProgress.currentLesson / batchProgress.totalLessons) * 100)}%
                      </span>
                    )}
                  </div>

                  {/* Progress bar */}
                  {batchProgress && (
                    <div className="w-full bg-gray-200 dark:bg-gray-700 rounded-full h-3">
                      <div
                        className="bg-gradient-to-r from-green-500 to-blue-500 h-3 rounded-full transition-all duration-500"
                        style={{ width: `${Math.round((Object.keys(batchLessonStatuses).length / batchProgress.totalLessons) * 100)}%` }}
                      />
                    </div>
                  )}

                  {/* Current lesson indicator */}
                  {batchProgress && batchProgress.status === 'generating' && (
                    <div className="flex items-center gap-2 text-sm text-blue-600 dark:text-blue-400">
                      <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                      </svg>
                      <span>
                        Generando: <strong>{batchProgress.lessonTitle}</strong>
                        <span className="text-gray-500 ml-1">({batchProgress.moduleTitle})</span>
                      </span>
                    </div>
                  )}

                  {/* Lesson statuses list */}
                  <div className="max-h-64 overflow-y-auto space-y-1">
                    {Object.entries(batchLessonStatuses).map(([lessonId, info]) => (
                      <div
                        key={lessonId}
                        className={`flex items-center justify-between text-sm py-1.5 px-3 rounded ${
                          info.status === 'completed'
                            ? 'bg-green-50 dark:bg-green-900/20'
                            : 'bg-red-50 dark:bg-red-900/20'
                        }`}
                      >
                        <div className="flex items-center gap-2 min-w-0">
                          {info.status === 'completed' ? (
                            <svg className="w-4 h-4 text-green-600 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                            </svg>
                          ) : (
                            <svg className="w-4 h-4 text-red-600 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                            </svg>
                          )}
                          <span className="text-gray-700 dark:text-gray-300 truncate">{info.title}</span>
                        </div>
                        <span className="text-xs text-gray-500 dark:text-gray-400 flex-shrink-0 ml-2">
                          {info.status === 'completed'
                            ? `${(info.contentLength / 1000).toFixed(1)}k chars`
                            : 'Error'}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Batch complete: Summary */}
              {batchComplete && batchSummary && (
                <div className="text-center py-6">
                  <div className={`w-16 h-16 mx-auto rounded-full flex items-center justify-center mb-4 ${
                    batchSummary.failed === 0 && !batchSummary.cancelled
                      ? 'bg-green-100 dark:bg-green-900/30'
                      : 'bg-yellow-100 dark:bg-yellow-900/30'
                  }`}>
                    {batchSummary.failed === 0 && !batchSummary.cancelled ? (
                      <svg className="w-8 h-8 text-green-600 dark:text-green-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                      </svg>
                    ) : (
                      <svg className="w-8 h-8 text-yellow-600 dark:text-yellow-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                      </svg>
                    )}
                  </div>
                  <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-2">
                    {batchSummary.cancelled ? 'Generacion Cancelada' : 'Generacion Completada'}
                  </h3>
                  <div className="flex justify-center gap-6 text-sm mb-4">
                    <span className="text-green-600 dark:text-green-400 font-medium">
                      {batchSummary.completed} completadas
                    </span>
                    {batchSummary.failed > 0 && (
                      <span className="text-red-600 dark:text-red-400 font-medium">
                        {batchSummary.failed} con error
                      </span>
                    )}
                    <span className="text-gray-500 dark:text-gray-400">
                      de {batchSummary.total} lecciones
                    </span>
                  </div>

                  {/* Error details */}
                  {batchSummary.errors && batchSummary.errors.length > 0 && (
                    <div className="mt-4 text-left bg-red-50 dark:bg-red-900/20 rounded-lg p-3 border border-red-200 dark:border-red-800">
                      <p className="text-sm font-medium text-red-700 dark:text-red-300 mb-2">Errores:</p>
                      {batchSummary.errors.map((err, i) => (
                        <p key={i} className="text-xs text-red-600 dark:text-red-400">
                          - {err.lessonTitle}: {err.error}
                        </p>
                      ))}
                    </div>
                  )}
                </div>
              )}
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-gray-200 dark:border-gray-700 flex items-center justify-between bg-gray-50 dark:bg-gray-900">
          {step === 1 && (
            <>
              <button
                onClick={handleClose}
                className="px-4 py-2 text-gray-600 dark:text-gray-400 hover:text-gray-800 dark:hover:text-gray-200 transition-colors"
              >
                Cancelar
              </button>
              <button
                onClick={handleGenerate}
                disabled={isGenerating || !topic.trim() || !goals.trim()}
                className="flex items-center gap-2 px-6 py-2 bg-gradient-to-r from-green-600 to-blue-600 text-white rounded-lg hover:from-green-700 hover:to-blue-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {isGenerating ? (
                  <>
                    <svg className="w-5 h-5 animate-spin" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                    <span>Generando...</span>
                  </>
                ) : (
                  <>
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                    </svg>
                    <span>Generar Estructura</span>
                  </>
                )}
              </button>
            </>
          )}

          {step === 2 && (
            <>
              <button
                onClick={() => setStep(1)}
                className="flex items-center gap-2 px-4 py-2 text-gray-600 dark:text-gray-400 hover:text-gray-800 dark:hover:text-gray-200 transition-colors"
              >
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
                </svg>
                Volver
              </button>
              <button
                onClick={handleApplyStructure}
                disabled={isApplying}
                className="flex items-center gap-2 px-6 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors disabled:opacity-50"
              >
                {isApplying ? (
                  <>
                    <svg className="w-5 h-5 animate-spin" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                    <span>Aplicando...</span>
                  </>
                ) : (
                  <>
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                    </svg>
                    <span>Aplicar Estructura</span>
                  </>
                )}
              </button>
            </>
          )}

          {step === 3 && (
            <>
              {/* Cancel button during generation */}
              {batchId && !batchComplete && (
                <button
                  onClick={handleCancelBatch}
                  className="flex items-center gap-2 px-4 py-2 text-red-600 dark:text-red-400 hover:text-red-800 dark:hover:text-red-300 transition-colors"
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                  </svg>
                  Cancelar
                </button>
              )}
              {/* Spacer when no left button */}
              {(!batchId || batchComplete) && <div />}

              {/* Close button after completion */}
              {batchComplete && (
                <button
                  onClick={handleFinishAndClose}
                  className="flex items-center gap-2 px-6 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"
                >
                  <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                  </svg>
                  Cerrar
                </button>
              )}
            </>
          )}
        </div>
      </div>
    </div>
  );
}

/**
 * ModuleEditor - Inline editor for a module
 */
function ModuleEditor({ module, onSave, onCancel }) {
  const [editedModule, setEditedModule] = useState({ ...module });

  const handleLessonChange = (index, field, value) => {
    const newLessons = [...editedModule.lessons];
    newLessons[index] = { ...newLessons[index], [field]: value };
    setEditedModule({ ...editedModule, lessons: newLessons });
  };

  const handleAddLesson = () => {
    setEditedModule({
      ...editedModule,
      lessons: [...editedModule.lessons, { title: 'Nueva leccion', duration_minutes: 20 }]
    });
  };

  const handleDeleteLesson = (index) => {
    if (editedModule.lessons.length <= 1) {
      toast.error('El modulo debe tener al menos una leccion');
      return;
    }
    const newLessons = editedModule.lessons.filter((_, i) => i !== index);
    setEditedModule({ ...editedModule, lessons: newLessons });
  };

  return (
    <div className="p-4 bg-blue-50 dark:bg-blue-900/20">
      <div className="space-y-4">
        {/* Module title */}
        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
            Titulo del Modulo
          </label>
          <input
            type="text"
            value={editedModule.title}
            onChange={(e) => setEditedModule({ ...editedModule, title: e.target.value })}
            className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white text-sm"
          />
        </div>

        {/* Description */}
        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
            Descripcion
          </label>
          <textarea
            value={editedModule.description}
            onChange={(e) => setEditedModule({ ...editedModule, description: e.target.value })}
            rows={2}
            className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white text-sm"
          />
        </div>

        {/* Lessons */}
        <div>
          <div className="flex items-center justify-between mb-2">
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300">
              Lecciones
            </label>
            <button
              onClick={handleAddLesson}
              className="text-sm text-primary-600 hover:text-primary-700 flex items-center gap-1"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
              </svg>
              Agregar
            </button>
          </div>
          <div className="space-y-2">
            {editedModule.lessons.map((lesson, index) => (
              <div key={index} className="flex items-center gap-2">
                <input
                  type="text"
                  value={lesson.title}
                  onChange={(e) => handleLessonChange(index, 'title', e.target.value)}
                  className="flex-1 px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white text-sm"
                  placeholder="Titulo de la leccion"
                />
                <input
                  type="number"
                  value={lesson.duration_minutes}
                  onChange={(e) => handleLessonChange(index, 'duration_minutes', parseInt(e.target.value) || 15)}
                  className="w-20 px-3 py-2 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white text-sm text-center"
                  min="5"
                  max="120"
                />
                <span className="text-sm text-gray-500">min</span>
                <button
                  onClick={() => handleDeleteLesson(index)}
                  className="p-1 text-gray-400 hover:text-red-600 transition-colors"
                >
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                  </svg>
                </button>
              </div>
            ))}
          </div>
        </div>

        {/* Actions */}
        <div className="flex justify-end gap-2">
          <button
            onClick={onCancel}
            className="px-3 py-1.5 text-sm text-gray-600 dark:text-gray-400 hover:text-gray-800 dark:hover:text-gray-200"
          >
            Cancelar
          </button>
          <button
            onClick={() => onSave(editedModule)}
            className="px-3 py-1.5 text-sm bg-primary-600 text-white rounded-lg hover:bg-primary-700"
          >
            Guardar
          </button>
        </div>
      </div>
    </div>
  );
}
